version: '3'
services:
  api:
    build: 
      context: .
      dockerfile: ./api/Dockerfile
    command: npm run start:api
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - HOST=http://realworld-docker.com
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db
  api_db:
    image: mongo:latest
  auth:
    build: 
      context: .
      dockerfile: ./auth/Dockerfile
    command: npm run start:auth
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HOST=http://realworld-docker.com
      - MONGO_URL=mongodb://auth_db:27017/auth
    depends_on:
      - auth_db
  auth_db:
    image: mongo:latest
  frontend:
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: weather_app_frontend
    command: serve -s build -l 3000
    environment:
      - NODE_ENV=prod
    ports:
      - "3000:3000"
    restart: unless-stopped
