version: '3'
services:
  weather_app:
    build: 
      context: .
      dockerfile: ./src/Dockerfile
    command: npm run start
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOST=http://realworld-docker.com
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db
  api_db:
    image: mongo:latest

